Allow specifying backend settings using an environment variable
kuzzleio/vue-plugin-kuzzle pull request #2
Opened 2019-04-27 16:40 UTC by BenjaminVadant

A possible solution to https://github.com/xbill82/vue-kuzzle/issues/1

2019-05-13 08:25 UTC, xbill82 requested changes
I totally agree with the need of keeping only the concerned backend exposed in the built code, but I don't like the idea of passing a stringified object in an environment variable. By the way, I think that it's not this plugin's concern to figure out which backend config the user wants. I prefer to leave the management of the backend config at App level and make the plugin talke a `backendOptions` object. 
The plugin just know the defaults values for this object.

2019-05-13 08:25 UTC, xbill82 commented on index.js
> +  if (process.env.VUE_KUZZLE_BACKEND) {
Let's take this whole check away.

2019-05-13 08:25 UTC, xbill82 commented on index.js
> +  if (!backendOptions) {
Let's just define the default backend options here:

```
import { defaultsDeep } from 'lodash';
const backend = defaultsDeep(backendOptions, {
  host: 'localhost',
  port: 7512,
  options: {
    sslConnection: false
    port: 7512,
   }
 });
```

2020-03-06 09:43 UTC, scottinet commented
This PR has been inactive for a long time => closing it.

2020-03-06 09:43 UTC, closed without merging