fix for vue3 compatibility
kuzzleio/vue-plugin-kuzzle pull request #4
Opened 2021-03-10 09:20 UTC by Erilan

Update install function to amtch Vue.js 3 new syntax.
I'm not sure about the package.json update I did

2021-03-10 09:55 UTC, Njuelle requested changes

2021-03-10 09:55 UTC, Njuelle commented on README.md
> +
```suggestion
```

2021-03-10 10:28 UTC, Erilan commented on README.md
> +
@Njuelle fixed :)

2021-03-10 10:37 UTC, jenow approved these changes

2021-03-10 12:59 UTC, Njuelle approved these changes

2021-03-10 12:59 UTC, merged

2025-06-27 08:21 UTC, kuzzle commented
:tada: This PR is included in version 1.0.0-vue3.1 :tada:

The release is available on:
- [npm package (@vue3 dist-tag)](https://www.npmjs.com/package/vue-plugin-kuzzle/v/1.0.0-vue3.1)
- [GitHub release](https://github.com/kuzzleio/vue-plugin-kuzzle/releases/tag/v1.0.0-vue3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: